# Generated by Django 4.0.6 on 2023-03-23 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'cvs',
                'verbose_name_plural': 'cvs',
                'db_table': 'cvs',
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeTire', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('rotation', models.BooleanField()),
                ('quantityRotate', models.IntegerField(blank=True)),
                ('duration', models.IntegerField()),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('bill', models.IntegerField()),
                ('idCustomer', models.IntegerField()),
                ('nameCustomer', models.TextField(max_length=50)),
                ('telCustomer', models.TextField(max_length=15)),
                ('dateScheduled', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(blank=True)),
                ('done', models.BooleanField(blank=True)),
                ('comment', models.TextField(blank=True, max_length=300)),
                ('cvs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.cvs')),
                ('modifiedBy', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_who_modifies', to='scheduling.profile')),
                ('scheduledBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_who_schedules', to='scheduling.profile')),
            ],
            options={
                'verbose_name': 'turn',
                'verbose_name_plural': 'turns',
                'db_table': 'turn',
            },
        ),
    ]
