# Generated by Django 4.0.6 on 2023-03-30 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_cvs_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turn',
            name='comment',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='turn',
            name='dateModified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turn',
            name='done',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turn',
            name='modifiedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_who_modifies', to='scheduling.profile'),
        ),
        migrations.AlterField(
            model_name='turn',
            name='quantityRotate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
