# Generated by Django 4.0.6 on 2023-05-25 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_alter_turn_comment_alter_turn_datemodified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('startDate', models.DateField()),
                ('startHour', models.TimeField()),
                ('endDate', models.DateField()),
                ('endHour', models.TimeField()),
                ('comment', models.TextField(blank=True, max_length=300, null=True)),
                ('cvs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.cvs')),
                ('scheduledBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_who_schedules_block', to='scheduling.profile')),
            ],
            options={
                'verbose_name': 'block',
                'verbose_name_plural': 'blocks',
                'db_table': 'block',
            },
        ),
    ]
