# Generated by Django 4.0.6 on 2023-07-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turn',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=300, null=True),
        ),
    ]
